export const DESKTOP_API_CONTRACT = {
  getRuntimeStatus: "runtime:getStatus",
  shutdownRuntime: "runtime:shutdown",
  selectWorkspace: "workspace:select",
  getWorkspaces: "workspace:list",
  getEngineeringProjectContext: "engineering:getProjectContext",
  runEngineeringCommand: "engineering:runCommand",
  createStructuredTask: "task:createStructured",
  createAssistantTask: "assistant:createTask",
  cancelAssistantTask: "assistant:cancelTask",
  answerClarification: "assistant:answerClarification",
  retryAssistantTask: "assistant:retryTask",
  continueAssistantTask: "assistant:continueTask",
  getTasks: "task:list",
  getTask: "task:get",
  getTaskCenterTasks: "taskCenter:list",
  getTaskCenterTask: "taskCenter:get",
  getApprovals: "approval:list",
  decideApproval: "approval:decide",
  undoAction: "undo:apply",
  getRegisteredApps: "host:registeredApps",
  getProviderSettings: "provider:getSettings",
  updateProviderSettings: "provider:updateSettings",
  saveProviderKey: "provider:saveKey",
  deleteProviderKey: "provider:deleteKey",
  testProvider: "provider:test",
  preloadReady: "diagnostics:preloadReady"
} as const;

export const DESKTOP_API_METHODS = [
  "getRuntimeStatus",
  "shutdownRuntime",
  "selectWorkspace",
  "getWorkspaces",
  "getEngineeringProjectContext",
  "runEngineeringCommand",
  "createStructuredTask",
  "createAssistantTask",
  "cancelAssistantTask",
  "answerClarification",
  "retryAssistantTask",
  "continueAssistantTask",
  "getTasks",
  "getTask",
  "getTaskCenterTasks",
  "getTaskCenterTask",
  "getApprovals",
  "decideApproval",
  "undoAction",
  "getRegisteredApps",
  "getProviderSettings",
  "updateProviderSettings",
  "saveProviderKey",
  "deleteProviderKey",
  "testProvider"
] as const;

export type DesktopApiMethod = (typeof DESKTOP_API_METHODS)[number];
export type IpcChannel = (typeof DESKTOP_API_CONTRACT)[keyof typeof DESKTOP_API_CONTRACT];
